### ISSUE TITLE
Tipbot creating extra accounts for users, which they cannot access.

### ISSUE THREAD

**Issue by filipnyquist** [LBRYFoundation/lbry-tipbot#5]
The problem could be caused by this:
https://github.com/lbryio/lbry-tipbot/blob/5c21d0fd22511152a3bace3635b8d3ddadfc46ab/bot/modules/tipbot.js#L106

**Comment by nikooo777** [comment]
The issue is most likely that we're using `members` rather than `users`
https://discord.js.org/#/docs/main/stable/class/GuildMember
https://discord.js.org/#/docs/main/stable/class/User

also we should be using the property .id of said user, this way whatever username they use, it won't matter.

Can you confirm?

**Comment by ProfessorDey** [comment]
Right, that's my mistake for not understanding how GuildMembers and Users were different, as the documentation doesn't do the best job of clarifying, so sorry about that.

Also my bad using let, I'm just an idiot in this case, saw the code above where tipper was defined and so used that instead of var.

Have put up pull request on here that should fix it, though it'll still require manually refunding the money from the accidentally created accounts. Link: https://github.com/lbryio/lbry-tipbot/pull/9

**Comment by ProfessorDey** [comment]
Have updated PR to match the latest commit of my other PR.
